spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:file:./db
    driver-class-name: org.h2.Driver
    username: sa
    password: pass
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect