spring:
  datasource:
    url: jdbc:h2:file:./db
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect